# IMPORTANT: secrets should never be checked-in to app repos; this is only for demo purposes
# echo -n 'some_word' | base64 - to get some_word in base64

apiVersion: v1                      # because Secret belongs to core k8s API group
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque                        # specific field for Secret component
data:
  mongo-root-username: ZGFuZGVsaW9u           # base64 encoded
  mongo-root-password: cHN3ZC1kYW5kZWxpb24=   # base64 encoded

# kubectl apply -f mongo-secret.yaml