apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret-dummy
type: Opaque
data:
  secret-data.txt: |        # pipe (|) is the syntax to create a file named secret-data.txt directly here (it's base64 encoded)
    dGhpcyBpcyBzb21lIHZlcnkgc2VjcmV0IGRhdGE=

# kubectl apply -f mosquitto-secret-dummy.yaml
