apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-configmap
data:
  mosquitto.conf: |   # this pipe (|) is the syntax for defining a file named "mosquitto.conf" directly in configmap
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001

# kubectl apply -f mosquitto-configmap.yaml
