apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: my-namespace
data:
  db_url: mysql-service.database	# .database means that mysql-service is within the "database" namespace

# kubectl get configmap 							            # this will NOT show mysql-configmap, because it only shows components from default namespace
# kubectl get configmap --namespace my-namespace	# this will shoh mysql-configmap
# kubectl get configmap -n my-namespace 			    # short
