apiVersion: rbac.authorization.k8s.io/v1          # RBAC = Role Based Access Control
kind: RoleBinding
metadata:
  name: jane-developer-binding
subjects:
  - kind: User
    name: jane
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-access
  apiGroup: rbac.authorization.k8s.io

  # RoleBinding needs to be created to bind the user to the rule